<?php 
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/css/reveal.min.css','','')
                 ->appendStylesheet($basePath . '/css/theme/default.css', '', true, array('id' => 'theme'))
                 ->appendStylesheet($basePath . '/lib/css/zenburn.css','','');
               

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . 'lib/js/html5shiv.js', 'text/javascript', 
    array('conditional' => 'lt IE 9',))
        ->appendScript('document.write( \'<link rel="stylesheet" href="/css/print/\' + ( window.location.search.match( /print-pdf/gi ) ? \'pdf\' : \'paper\' ) + \'.css" type="text/css" media="print">\'', 'text/css', array('noescape' => true));

echo $this->doctype();?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Presentation') ?>
    
    <?php echo $this->headMeta()->appendName('description', '')
                ->appendName('keywords', '')
                ->appendName('author', '')
                ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
                ->appendName('apple-mobile-web-app-capable', 'yes') 
                ->appendName('apple-mobile-web-app-status-bar-style', 'black-translucent') ?>
    
    
    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <!-- Scripts -->
    <?php echo $this->headScript() ?>
    
    <?php
        $title = 'My Presentation';
        $this->headTitle($title);
    ?>
  </head>
<!doctype html>
<html lang="en">
	<body>
              <?php echo $this->escapeHtml($presentation->content);?>
            <?php echo $presentation->content;?>
	</body>
</html>
