<?php


$title = 'My presentations';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('presentation', array('action'=>'add'));?>">Add new presentation</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Private</th>
    <th>Theme</th>
    <th>Timestamp</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($presentations as $presentation) : ?>
<tr>
    <td><?php echo $this->escapeHtml($presentation->title);?></td>
    <td><?php echo $this->escapeHtml($presentation->private);?></td>
    <td><?php echo $this->escapeHtml($presentation->theme);?></td>
    <td><?php echo $this->escapeHtml($presentation->timestamp);?></td>
    <td>
        <a href="<?php echo $this->url('presentation',
            array('action'=>'view', 'id' => $presentation->id));?>">View</a>
        <a href="<?php echo $this->url('presentation',
            array('action'=>'edit', 'id' => $presentation->id));?>">Edit</a>
        <a href="<?php echo $this->url('presentation',
            array('action'=>'delete', 'id' => $presentation->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>