<?php 
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/css/reveal.min.css','','')
                 ->appendStylesheet($basePath . '/css/theme/default.css', '', true, array('id' => 'theme'))
                 ->appendStylesheet($basePath . '/lib/css/zenburn.css','','');
               

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . 'lib/js/html5shiv.js', 'text/javascript', 
    array('conditional' => 'lt IE 9',))
        ->appendScript('document.write( \'<link rel="stylesheet" href="/css/print/\' + ( window.location.search.match( /print-pdf/gi ) ? \'pdf\' : \'paper\' ) + \'.css" type="text/css" media="print">\'', 'text/css', array('noescape' => true));

echo $this->doctype();?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Presentation') ?>
    
    <?php echo $this->headMeta()->appendName('description', '')
                ->appendName('keywords', '')
                ->appendName('author', '')
                ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
                ->appendName('apple-mobile-web-app-capable', 'yes') 
                ->appendName('apple-mobile-web-app-status-bar-style', 'black-translucent') ?>
    
    
    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <!-- Scripts -->
    <?php echo $this->headScript() ?>
    
    <?php
        $title = 'My Presentation';
        $this->headTitle($title);
    ?>
  </head>
<!doctype html>
	<body>
            
            <?php echo $presentation->content;?>
     		
            
                

	
                
                
                
                <?php
                $this->inlineScript()->appendFile($basePath . '/lib/js/head.min.js')
                                    ->appendFile($basePath . '/js/reveal.min.js')
                                    ->appendFile($basePath . '/plugin/highlight/highlight.js', 'text/javascript')
                                    ->appendFile($basePath . '/plugin/zoom-js/zoom.js', 'text/javascript')
                                    ->appendFile($basePath . '/plugin/notes/notes.js', 'text/javascript')
                                    
                                    // ->appendScript('document.write( \'<link rel="stylesheet" href="/css/print/\' + ( window.location.search.match( /print-pdf/gi ) ? \'pdf\' : \'paper\' ) + \'.css" type="text/css" media="print">\'', 'text/css', array('noescape' => true));
                ?>
                
                <!-- Scripts -->
                <?php echo $this->inlineScript() ?>
                	
                
                <script>

			// Full list of configuration options available here:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				
                                controls: <?php echo $presentation->controls;?>,
                                progress: <?php echo $presentation->progress;?>,
                                history: <?php echo $presentation->history;?>,
                                center: <?php echo $presentation->center;?>,
                                keyboard: <?php echo $presentation->keyboard;?>,
                                overview :<?php echo $presentation->overview;?>,
                                loop: <?php echo $presentation->looop;?>,
                                rtl: <?php echo $presentation->rtl;?>,
                                mouseWeel: <?php echo $presentation->mouseWeel;?>,
                                rollingLinks: <?php echo $presentation->rollingLinks;?>,
                                presetationWidth: <?php echo $presentation->presetationWidth;?>,
                                presentationHeight: <?php echo $presentation->presentationHeight;?>,
                                presentationMargin: <?php echo $presentation->presentationMargin;?>,
                                presentationMinScale: <?php echo $presentation->presentationMinScale;?>,
                                presentationMaxScale: <?php echo $presentation->presentationMaxScale;?>,
                                autoSlide: <?php echo $presentation->autoSlide;?>,
                                
                                
				theme: Reveal.getQueryHash().theme, // available themes are in /css/theme
				transition: Reveal.getQueryHash().transition || '<?php echo $presentation->transition;?>', // default/cube/page/concave/zoom/linear/fade/none

				// Optional libraries used to extend on reveal.js
				dependencies: [
					{ src: '/lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: '/plugin/markdown/showdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: '/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: '/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: '/plugin/zoom-js/zoom.js', async: true, condition: function() { return !!document.body.classList; } },
					{ src: '/plugin/notes/notes.js', async: true, condition: function() { return !!document.body.classList; } }
					// { src: '/plugin/search/search.js', async: true, condition: function() { return !!document.body.classList; } }
					// { src: '/plugin/remotes/remotes.js', async: true, condition: function() { return !!document.body.classList; } }
				]
			});

		</script>
	</body>
</html>
